// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package testing

import (
	"context"

	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service testing.
type RPCService interface {
	TestingEnableDisable(ctx context.Context, in *TestingEnableDisable) (*TestingEnableDisableReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) TestingEnableDisable(ctx context.Context, in *TestingEnableDisable) (*TestingEnableDisableReply, error) {
	out := new(TestingEnableDisableReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
